model:
  name: 'rnn_1hl'
  input_size: 1
  hidden_size: 10
  output_size: 1
training:
  gradient_computation: 'wp'  # 'wp' or 'bptt'
  epochs: 1000
  learning_rate: 0.0002
  seed: 12
  perturbation: 0.001
  clip: True
  max_clip_value: 3
  min_clip_value: -3
log:
  log_file: 'src\log.txt'
  experiment_name: 'rnn_1hl on sine data'