model:
  name: 'rnn_1hl'
  input_size: 1
  hidden_size: 10
  output_size: 2
training:
  gradient_computation: 'wp'  # 'wp' or 'bptt'
  epochs: 15
  learning_rate: 'step' #0.00001
  seed: 12
  perturbation: 0.00001
  clip: True
  max_clip_value: 3
  min_clip_value: -3
log:
  experiment_name: 'rnn_1hl on chemotaxis data'
